<?php
/**
 * @var $this       Mage_Catalog_Block_Product_View_Media
 * @var $product    Mage_Catalog_Model_Product
 */
?>
<?php
    $product = $this->getProduct();
    $outputHelper = $this->helper('catalog/output');
    $helper = $this->helper('shoppersettings/image');
    $config = Mage::getStoreConfig('shoppersettings');
    $_embedded      = Mage::getStoreConfig('wr360_product_view/standard/embedded');
    $_360ViewWidth  = Mage::getStoreConfig('wr360_product_view/settings/popup_width');
    $_360ViewHeight = Mage::getStoreConfig('wr360_product_view/settings/popup_height');
    $_thumbWidth    = Mage::getStoreConfig('wr360_product_view/standard/thumb_width');
    $_thumbHeight   = Mage::getStoreConfig('wr360_product_view/standard/thumb_height');
    $_licensePath   = Mage::getStoreConfig('wr360_product_view/settings/license');
    $_360root       = $product->getData('webrotate_root');
    $_360path       = $product->getWebrotatePath();
    $_prettyTheme   = Mage::getStoreConfig('wr360_product_view/settings/pretty_theme');
    $_360icon       = Mage::getStoreConfig('wr360_product_view/settings/popup_icon');
    $_rootPathMode  = false;


    list($defaultImgX, $defaultImgY) = $helper->getDefaultSize();
    list($imgX, $imgY) = $helper->getMainSize();
    if ( $imgX > 800 ) {
        $imgX = 800;
        $imgY = $helper->calculateHeight($imgX);
    }
    list($thumbX, $thumbY) = $helper->getThumbSize();

    //cloud Zoom config
    $config['cloudzoom']['position'] =  empty($config['cloudzoom']['position']) ? 'right' : $config['cloudzoom']['position'];
    $config['cloudzoom']['lens_opacity'] = intval($config['cloudzoom']['lens_opacity']) / 100;
    $config['cloudzoom']['tint_opacity'] = intval($config['cloudzoom']['tint_opacity']) / 100;


  if (empty($_360path))
    {
        $_360path = Mage::getStoreConfig('wr360_product_view/settings/master_config');
        $_rootPathMode = true;
    }

    if (empty($_360icon))
    {
        $_360icon = $this->getSkinUrl('webrotate360/360thumb.png');
    }

    $_360IsSet = ((($_rootPathMode == false) && !empty($_360path)) || (($_rootPathMode == true) && !empty($_360root)))
?>
<?php if ( $config['cloudzoom']['position'] == 'inside' ) : ?>
<style>
.cloud-zoom-big { margin:0; -moz-box-shadow:none; -webkit-box-shadow:none; box-shadow:none; }
</style>
<?php endif; ?>


    <?php
        $cloudZoom = array(
            "position:'".$config['cloudzoom']['position']."'",
            "showTitle:false",
            "lensOpacity:".$config['cloudzoom']['lens_opacity'],
            "smoothMove:".$config['cloudzoom']['smooth_move'],
        );
        if ($config['cloudzoom']['zoom_width'] > 0) {
            $cloudZoom[] = "zoomWidth:".$config['cloudzoom']['zoom_width'];
        }
        if ($config['cloudzoom']['zoom_height'] > 0) {
            $cloudZoom[] = "zoomHeight:".$config['cloudzoom']['zoom_height'];
        }

        if ($config['cloudzoom']['tint_color']) {
            $cloudZoom[] = "tint:'".$config['cloudzoom']['tint_color']."',tintOpacity:".$config['cloudzoom']['tint_opacity'];
        }
        if ($config['cloudzoom']['soft_focus'] > 0) {
            $cloudZoom[] = "softFocus:".$config['cloudzoom']['soft_focus'];
        }

        if ( empty($config['cloudzoom']['big_image_width']) || empty($config['cloudzoom']['big_image_height']) ) {
            if ( empty($config['cloudzoom']['big_image_width']) || $config['cloudzoom']['big_image_width'] > 1200 ) {
                $config['cloudzoom']['big_image_width'] = 1000;
            }
            if ( empty($config['cloudzoom']['big_image_height']) ) {
                $config['cloudzoom']['big_image_height'] = $this->helper('shoppersettings/image')->calculateHeight($config['cloudzoom']['big_image_width']);
            }
        }
    ?>

    <?php
    $_hideDisplay = 'block'; 
    if($_360IsSet && $_embedded):
        $_hideDisplay = 'none'; 
    ?>
        <div class="360-images">
            <div style="width:<?php print((strpos($_360ViewWidth, '%') === FALSE) ? $_360ViewWidth.'px' : $_360ViewWidth) ?>; height:<?php echo $_360ViewHeight.'px' ?>;" id="wr360PlayerId" class="wr360_player">
                <script language="javascript" type="text/javascript">
                    _imageRotator.licenseFileURL = "<?php echo $_licensePath ?>";
                    _imageRotator.settings.configFileURL = "<?php echo $_360path ?>";
                    _imageRotator.settings.graphicsPath = "<?php echo $this->getSkinUrl('webrotate360/imagerotator/html/img/basic') ?>" ;
                    _imageRotator.settings.rootPath = "<?php echo $_360root ?>";
                    _imageRotator.runImageRotator("wr360PlayerId");
                </script>
            </div>
        </div>
    <?php endif ?>
        <div class="product-image" style="display:<?php echo $_hideDisplay; ?>">
            <a href="<?php echo $product->getCustomImageUrl(true) ?>" class="cloud-zoom" id="cloud_zoom" rel="<?php echo implode($cloudZoom, ',');?>">
                <img src="<?php echo $product->getCustomImageUrl(); ?>" data-srcX2="<?php echo $product->getCustomImageUrl(true); ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel());?>" title="<?php echo $this->escapeHtml($this->getImageLabel());?>" width="<?php echo $imgX;?>" height="<?php echo $imgY;?>" />
            </a>
        </div>
<?php $nb_images = $product->getNbImages();
?>
<?php if ($nb_images > 0): ?>
<div class="more-views">
    <ul id="shopper_gallery_carousel" class="jcarousel-skin-tango clearfix">
    <?php if($_360IsSet && $_embedded): ?>
        <li style="width:126px; height:126px; line-height:126px;">
            <a href="" class="360-thumbnail">
                <img src="<?php echo $_360icon ?>" />
            </a>
        </li>
    <?php endif; ?>
    <?php for($i=1; $i <= $nb_images; $i++): ?>
        <li>
            <a href="<?php echo $product->getCustomImageUrl(true, $i); ?>" class="cloud-zoom-gallery"
            rel="useZoom: 'cloud_zoom', smallImage: '<?php echo  $product->getCustomImageUrl(false, $i); ?>' ">
            <img src="<?php echo $product->getCustomImageUrl(false, $i); ?>" data-srcX2="<?php echo $product->getCustomImageUrl(true,$i); ?>" width="<?php echo $thumbX; ?>" height="<?php echo $thumbY; ?>" />
            </a>
        </li>
    <?php endfor; ?>
    </ul>
    <div class="jcarousel-controls">
        <a href="#" class="jcarousel-prev-horizontal" id="shopper_gallery_prev"></a>
        <a href="#" class="jcarousel-next-horizontal" id="shopper_gallery_next"></a>
    </div>
</div>
<?php if ($_360IsSet && !$_embedded): ?>
    <script language="javascript" type="text/javascript">
        WR360IFrameParams = function()
        {
            this.configFileURL = "<?php echo $_360path ?>";
            this.rootPath = "<?php echo $_360root ?>";
            this.licensePath = "<?php echo $_licensePath ?>";
            this.graphicsPath = "<?php echo $this->getSkinUrl('webrotate360/imagerotator/html/img/basic') ?>";
        }
    </script>
<?php endif?>
<script language="javascript" type="text/javascript">
    <?php if ($_prettyTheme == "default"):?>
        jq360(document).ready(function(){
            jq360("a[rel^='prettyPhoto']").prettyPhoto();
        });
    <?php else:?>
        jq360(document).ready(function(){
            jq360("a[rel^='prettyPhoto']").prettyPhoto({theme:"<?php echo $_prettyTheme ?>"});
        });
    <?php endif?>
    jQuery(document).ready(function($) {
        jQuery('.360-thumbnail').click(function() {
            $('.product-image').hide();
            $('.360-images').show();
            return false;
        })
        myCarousel = null; // This will be the carousel object

        function mycarousel_initCallback(carousel, state) {
            if (state == 'init') {
                myCarousel = carousel;
            }
            $('#shopper_gallery_next').bind('click', function() {
                carousel.next();
                return false;
            });
            $('#shopper_gallery_prev').bind('click', function() {
                carousel.prev();
                return false;
            });

            $('.product-view .product-img-box .more-views .jcarousel-skin-tango .jcarousel-container-horizontal').width(<?php echo ($thumbX+8)*3;?>);
            $('.product-view .product-img-box .more-views .jcarousel-skin-tango .jcarousel-clip-horizontal').width(<?php echo ($thumbX+8)*3;?>);
            $('.product-view .product-img-box .more-views .jcarousel-skin-tango .jcarousel-item').width(<?php echo $thumbX;?>);
            $('#shopper_gallery_prev, #shopper_gallery_next').css({marginTop:-<?php echo ($thumbX)/2+17;?>});

        };

        $('#shopper_gallery_carousel').jcarousel({
            scroll: 1,
            initCallback: mycarousel_initCallback,
            buttonNextHTML: null,
            buttonPrevHTML: null
        });

        $(window).resize(function(){
            var n = $('#shopper_gallery_carousel > li').length;
            var w = $('#shopper_gallery_carousel > li').outerWidth(true);
            $('#shopper_gallery_carousel').width(n*w);
            myCarousel.scroll(0);
        });


        function mousetrap_click() {
            var images = [];
            images.push($('#cloud_zoom').attr('href'));
            $('a.cloud-zoom-gallery').each(function(){
                images.push($(this).attr('href'));
            });
            $.fancybox(
                images,
                {
                    'padding'           : 0,
                    'transitionIn'      : 'none',
                    'transitionOut'     : 'none',
                    'type'              : 'image',
                    'changeFade'        : 0
                }
            );
            return false;
        }

        if(jQuery('.cloud-zoom-gallery').length > 1) {
            $('.mousetrap').live('click', mousetrap_click);
        } else {
            $('.more-views').hide()
        }

        jQuery('.cloud-zoom').each(function() {
            self = jQuery(this);
            var url = self.attr('href');
            var img = new Image();
            console.log(url);
            img.src = url;
            jQuery(img).load(function() {
                if(img.width < 652) { 
                    jQuery('.product-image').on('mouseover', function() {
                        jQuery('.cloud-zoom-big').hide();
			jQuery('.cloud-zoom-lens').hide();
                    });
                }
            });
        });
    });
</script>
<?php endif; ?>
