<?php
    if (!empty($GLOBALS["WR360_ADHOC_SET"]))
        return;

    $GLOBALS["WR360_ADHOC_SET"] = true;
    $_product = Mage::registry('current_product');
    if (!$_product)
        return;

    $_rootPathMode  = false;
    $_360ViewWidth  = Mage::getStoreConfig('wr360_product_view/settings/popup_width');
    $_360ViewHeight = Mage::getStoreConfig('wr360_product_view/settings/popup_height');
    $_licensePath   = Mage::getStoreConfig('wr360_product_view/settings/license');
    $_360root       = $_product->getData('webrotate_root');
    $_360path       = $_product->getData('webrotate_path');
    $_graphicsPath  = Mage::getDesign()->getSkinUrl().'webrotate360/imagerotator/html/img/basic';
    $_placeholder   = Mage::getStoreConfig('wr360_product_view/adhoc/placeholder');
    $_embedded      = Mage::getStoreConfig('wr360_product_view/adhoc/embedded');
    $_prettyTheme   = Mage::getStoreConfig('wr360_product_view/settings/pretty_theme');
    $_360icon       = Mage::getStoreConfig('wr360_product_view/settings/popup_icon');

    if (empty($_360path))
    {
        $_360path = Mage::getStoreConfig('wr360_product_view/settings/master_config');
        $_rootPathMode = true;
    }

    $_360IsSet = ((($_rootPathMode == false) && !empty($_360path)) || (($_rootPathMode == true) && !empty($_360root)));
    if ($_360IsSet)
    {
        $_360path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$_360path;
    }

    if (empty($_360icon))
    {
        $_360icon = $this->getSkinUrl('webrotate360/360thumb.png');
    }
?>
<?if ($_360IsSet): ?>
    <?if ($_embedded):?>
        <style type="text/css">
            <?php echo $_placeholder?>{visibility: hidden;}
            .zoom-notice{display: none !important;}
            .zoom{display: none !important;}
        </style>
        <script language="javascript" type="text/javascript">
            jQuery(document).ready(function(){
                WR360AdhocEmbedInitialize(
                    "<?php echo $_placeholder?>",
                    "<?php echo $_360ViewWidth?>",
                    "<?php echo $_360ViewHeight?>",
                    "<?php echo $_graphicsPath?>",
                    "<?php echo $_360path?>",
                    "<?php echo $_360root?>",
                    "<?php echo $_licensePath?>");
            });
        </script>
    <?else:?>
        <style type="text/css">
            <?php echo $_placeholder?>{visibility: hidden;}
        </style>
        <script language="javascript" type="text/javascript">
            <?php $_360ViewWidth  = preg_replace("/[^0-9]/","",$_360ViewWidth) ?>
            <?php $_360ViewHeight = preg_replace("/[^0-9]/","",$_360ViewHeight) ?>

            jQuery(document).ready(function(){
                WR360AdhocPopupInitialize(
                    "<?php echo $_placeholder?>",
                    "<?php echo $this->getSkinUrl('webrotate360/frame.html').'?iframe=true&width='.$_360ViewWidth.'&height='.$_360ViewHeight ?>",
                    "<?php echo $_360icon ?>",
                    "<?php echo $_prettyTheme?>");
            });

            WR360IFrameParams = function(){
                this.configFileURL = "<?php echo $_360path ?>";
                this.rootPath = "<?php echo $_360root ?>";
                this.licensePath = "<?php echo $_licensePath ?>";
                this.graphicsPath = "<?php echo $_graphicsPath ?>";
            }
        </script>
    <?endif?>
<?endif?>
