<?php
$categ_ids = array(34,30);

$products = array();
$_helper = $this->helper('catalog/output');
$helper = $this->helper('shoppersettings/image');
foreach($categ_ids as $categ_id) {
    $category = new Mage_Catalog_Model_Category();
    $category->load($categ_id);
    $collection = $category->getProductCollection();
    $collection->addAttributeToSelect('name','sku');
    if(count($collection) > 0){
        $products = $collection;
        break;
    }
}
$_collectionSize = 0;
if(sizeof($products) > 0)
	$_collectionSize = $products->count();

$pageLayout = $this->getLayout()->getBlock('root')->getTemplate();
if ( strpos($pageLayout, '2columns') ) {
    $grid_class = 'two_columns_' . Mage::getStoreConfig('shoppersettings/catalog/grid_columns_2col');
} else {
    $grid_class = 'one_column_' . Mage::getStoreConfig('shoppersettings/catalog/grid_columns_1col');
}
$imgX = 270;
$imgY = $helper->calculateHeight($imgX);
?>
<div class="std">
    <h1 style="margin-bottom:20px;">Home</h1>
</div>
<hr />
<h3><?php echo $this->__('Coming Soon'); ?></h3>
<div class="slider2">
<div class="fullwidthbanner-container">
    <div class="fullwidthbanner2">
        <ul class="slides">
            <?php $i = 0;
            foreach ($products as $_product):
                $i += 1;
                if($i == 1):
            ?>
            <li data-transition="slidehorizontal">
                <ul class="products-grid <?php echo $grid_class; ?>">
                <?php endif; ?>
                        <li class="item">
                                        <div class="regular">
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                                <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
                                                <img src="<?php echo $_product->getCustomImageUrl(); ?>"  width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                            </a>
                                            <div class="product-info">
                                                <div class="button-container">
                                                    <?php if($_product->isSaleable()): ?>
                                                        <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>
                                                            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                                                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                                            <?php } else { ?>
                                                                <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                                            <?php }  ?>
                                                        <?php else: ?>
                                                            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                                        <?php endif; ?>                        
                                                    <?php endif; ?>
                                                </div>
                                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                                <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><strong><?php echo $_product->getSku(); ?></strong><br /> <?php  echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                                                <?php if($this->helper('customer')->isLoggedIn()) echo $this->getPriceHtml($_product, true) ?>
                                            </div>
                                        </div>
                                    <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
                                        <div class="hover">
                                            <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : //quick view button ?>
                                                <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' data-fancybox-group="gallery" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('quick view')?></a>
                                            <?php endif; ?>
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                                <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
                                                <?php
                                                $_product->load('media_gallery');
                                                $back_img = $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                                                if ( $back_img ) : ?>
                                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX, $imgY) ?>"  width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                                <?php else : ?>
                                                    <img src="<?php echo $_product->getCustomImageUrl(); ?>" data-srcX2="<?php echo $_product->getCustomImageUrl(true); ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                                <?php endif; ?>
                                            </a>
                                            
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                                    <?php echo $this->helper('shoppersettings/data')->priceFormat( $this->getPriceHtml($_product, true) ); ?>
                                                </a>
                                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                            <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><strong><?php echo $_product->getSku(); ?></strong><br /> <?php  echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                                            <?php if($_product->getRatingSummary()){ echo $this->getReviewsSummaryHtml($_product); } ?>
                                            <div class="button-container">
                                                <?php if($_product->isSaleable()): ?>

                                                    <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>

                                                        <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                                            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                                        <?php } else { ?>
                                                            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                                        <?php }  ?>

                                                    <?php else: ?>
                                                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
                                                <?php if($_product->getCustomStatus() == 5 and $_product->getCustomProductQty() <= 0): ?>
                                                    <span class="custom_status_4"><?php echo $this->__('Backorder'); ?></span>
                                                <?php else: ?>
                                                    <span class="custom_status_<?php echo $_product->getCustomStatus(); ?>"><?php echo $_product->getAttributeText('custom_status'); ?></span>
                                                <?php endif; ?>
                                                (<?php echo (int) $_product->getCustomProductQty(); ?>)
                                                <?php endif;?>

                                                
                                            </div>

                                            <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId()?>'><img src='<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>'/></span>

                                            <ul class="add-to-links">
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" data-id="<?php echo $_product->getId(); ?>"><span>+</span><?php echo $this->__('Add to Wishlist') ?></a></li>
                                                <?php endif; ?>
                                                <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)) : ?>
                                                <li><a href="<?php echo $_compareUrl ?>" class="link-compare" data-id="<?php echo $_product->getId(); ?>"><span>+</span><?php echo $this->__('Add to Compare') ?></a></li>
                                                <?php endif; ?>
                                            </ul>

                                        </div>
                        </li>
                    <?php endif;?>
                        <?php if($i == 3): ?>
            </ul>
            <?php
            $i = 0;
            endif; ?>
            <?php endforeach;
            if($i > 0){ ?>
                </ul>
            <?php }
            ?>
            </ul>
        </div>
    </div>
</div>
