ttraffic_lights.phtml
<?php
$_product = $this->getProduct();
/*<?php if($_product->getCustomStatus() == 5 and $_product->getCustomProductQty() <= 0): ?>
    <span class="custom_status_4"><?php echo $this->__('Backorder'); ?></span>
<?php else: ?>
    <span class="custom_status_<?php echo $_product->getCustomStatus(); ?>"><?php echo $_product->getAttributeText('custom_status'); ?></span>
<?php endif; ?>
(<?php echo (int) $_product->getCustomProductQty(); ?>)
// echo $_product->getName();
/**<?php if($_product->isSaleable() == True): ?>
    <img src="/skin/frontend/shopper/default/assets/traffic-lights-green-icon.png" />
<?php elseif($_product->getCustomStatus() == 3): ?>
    <img src="/skin/frontend/shopper/default/assets/traffic-lights-none-icon.png" />
<?php elseif($_product->getCustomStatus() == 4): ?>
    <img src="/skin/frontend/shopper/default/assets/traffic-lights-red-icon.png" />
<?php else: ?>
    <img src="/skin/frontend/shopper/default/assets/traffic-lights-yellow-icon.png" />
<?php endif; ?>**/
?>