<div class="home_page_buttons">
    <p>
	    <a href="/about-us.html">
		<img src="/skin/frontend/shopper/default/images/button-1.png" />
		<span>About Us</span>
	    </a>
    </p>
    <p>
	    <a href="/blog">
		<img src="/skin/frontend/shopper/default/images/button-2.png" />
		<span>News</span>
	    </a>
    </p>
    <p>
    	    <a href="http://catalogue.sparkmodel.com" target="_blank">
		<img src="/skin/frontend/shopper/default/images/button-3.png" />
		<span>Catalogue</span>
	    </a>
    </p>
	
    <!--<a href="/about-us.html">
        <button class="button" title="Subscribe">
            <span><span>About Us</span></span>
        </button>
    </a>
    <a href="/blog">
        <button class="button" title="Subscribe">
            <span><span>News</span></span>
        </button>
    </a>
    <a href="http://catalogue.sparkmodel.com" target="_blank">
        <button class="button" title="Subscribe">
            <span><span>Catalogue</span></span>
        </button>
    </a>-->
</div>
