<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>

<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
	<div class="block-content clearfix information">
			<ul id="<?php echo $this->getListId() ?>">
			<?php foreach($posts as $post): ?>
				<li class="item">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?> - <?php echo $this->htmlEscape(preg_replace('/([A-Za-z]{3})([A-Za-z]+)/', '$1', $post->getPostDate())); ?></a>
				</li>
			<?php endforeach; ?>
                <li class="item">
                    <a href="/blog"><?php echo _('Previous newsletters'); ?></a>
                </li>
			</ul>
	</div>
<?php endif; ?>
